[package]
name = "harsha"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "harsha_bin"
path = "src/main.rs"  # Path to your binary source file


[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
